### DISCUSSION TITLE
Custom Theme [自定义主题] 简单银白主题

### DISCUSSION THREAD

**Discussion by aliyoung** [crimx/ext-saladict#1446] [Theme 主题]
```css
/* 复制代码到「选项 -> 查词面板 -> 自定义查词面板样式」即可。*/

/* Root */
.dictPanel-Root {
  --color-background: #f5f8fa;
  --color-brand: #f5f8fa;
  --color-rgb-background: 34, 34, 34;
  --color-font: #000;
  --color-rgb-background: 255, 255, 255;

  background-color: #f5f8fa;
}

/* 输入框 */
.menuBar-SearchBox {
  background-color: transparent;
  color: #000;
}

/* 右上图标 */
.menuBar-Btn svg:not(.menuBar-Btn_Icon-fav) {
  fill: #000;
}

/* 收藏图标 */
.menuBar-Btn svg.menuBar-Btn_Icon-fav {
  stroke: #000;
}

/* 词典头部 */
.dictItemHead {
  align-items: center;
  padding-top: 10px;
}

/* 词典LOGO */
.dictItemHead-Logo {
  margin-left: 5px;
}

/* 词典空白区 */
.dictItemHead-EmptyArea {
  cursor: pointer;
  height: 20px;
  align-self: auto;
}

/* 隐藏文本输入区 */
.mtaBox-DrawerBtn {
  height: 0;
  border-bottom: none;
}
```
