### DISCUSSION TITLE
Custom Theme [自定义主题] 简单暗色主题

### DISCUSSION THREAD

**Discussion by zjuyk** [crimx/ext-saladict#1447] [Theme 主题]
默认的暗色主题是比较丑的，于是我从 github dimmed 主题中提取了部分颜色做了一份主题

![2021-08-20_21-07Portable Network Graphic file (PNG) (*](https://user-images.githubusercontent.com/76436317/130237841-31740212-5416-4318-b5dd-7781590b9c7f.png)

代码如下：

```css
/* 复制代码到「设置 -> 查词面板 -> 自定义查词面板样式」即可。*/
.dictPanel-Root {
  --color-brand: #22272e !important;
  --color-background: #2d333b !important;
  --color-font: #ddd !important;
  --color-divider: #4d4748 !important;
}

/* 滚动条颜色 */
.fancy-scrollbar {
  background-color: #2D333B !important;
}

/* 词典与顶部间隔 */
.dictItemHead {
  padding-top: 10px;
}

/* 词典图标右移 */
.dictItemHead-Logo {
  margin-left: 8px;
}

/* 取消文本输入区 */
.mtaBox-TextArea-Wrap {
  display: none;
}

/* 隐藏下拉按钮 */
.mtaBox-DrawerBtn {
  height: 0;
  border-bottom: none;
}
```
