### DISCUSSION TITLE
Custom Theme [自定义主题] [德古拉主题，配色来自Dracula Theme]

### DISCUSSION THREAD

**Discussion by jokergaming** [crimx/ext-saladict#1472] [Theme 主题]
```css
/* 复制代码到「设置 -> 查词面板 -> 自定义查词面板样式」即可。*/
.dictPanel-Root {
  --color-brand: #282a36 !important;
  --color-background: #282a36 !important;
  --color-font: #50fa7b !important;
  --color-divider: #282a36 !important;
}

/* 滚动条颜色 */
.fancy-scrollbar {
  background-color: #282a36 !important;
}

/* 词典与顶部间隔 */
.dictItemHead {
  padding-top: 10px;
}


.dictItemHead-Logo {
  margin-left: 10px;
}

/* 取消文本输入区 */
.mtaBox-TextArea-Wrap {
  display: none;
}

.mtaBox-DrawerBtn {
  height: 0;
  border-bottom: none;
}
```
