### DISCUSSION TITLE
Custom Theme [自定义主题] 极简主题 Nexmoe

### DISCUSSION THREAD

**Discussion by nexmoe** [crimx/ext-saladict#1567] [Theme 主题]
https://github.com/nexmoe/saladict-skin
![68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6e65786d6f652f696d616765406c61746573742f37343766376631613633633038336665336334376266393732326566333330642e706e67](https://user-images.githubusercontent.com/16796652/143368963-ede72108-56ce-45ef-b9cc-bd6534065d46.png)

**Comment by aliyoung** [comment]
给改了下，把搜索框显示了出来

![image](https://user-images.githubusercontent.com/694294/155114720-d984020d-7127-49b5-9197-3c9e8086fe8f.png)

```css
.menuBar {
  background-color: #fff;
  border-bottom: 1px solid #eee;
  padding: 8px;
}

.menuBar-SearchBox_Wrap {
  padding-right: 5px;
}

.menuBar-SearchBox {
  color: #000;
  background-color: #eee;
  padding: 8px 10px;
  border-radius: 10px;
}

.menuBar-Btn_Icon,
.menuBar-Btn_Icon-fav,
.menuBar-Btn_Icon-history {
  fill: #222;
}

.mtaBox-TextArea-Wrap,
.mtaBox-DrawerBtn,
.waveformBox.saladict-external,
.dictItemHead-Logo {
  display: none;
}

.dictItem {
  padding: 0 10px;
}

.dictItem:first-child {
  padding-top: 10px;
}

.dictItem-Body {
  padding: 0 3px;
}

.dictItemHead {
  background: #eee;
  border-radius: 6px;
  padding: 6px;
  height: auto;
}

.dictPanel-Root {
  box-shadow: rgba(0, 0, 0, 0.2) 0 7px 21px 2px;
}

.isAnimate .menuBar-Btn,
.isAnimate .menuBar-Btn-dir {
  border-radius: 6px;
}
```

**Comment by lasdocas** [comment]
这个主题很不错！想请问一下，如何让不同的字典拥有不同的背景色呢？

我瞎蒙了一个，把Vocabulary的主题色设置成浅绿色

d-vocabulary{
  background-color: #eafaea;
}

但是，牛津高阶设置成浅蓝色，我就蒙不出来了……

**Reply by crimx** [reply]
每个词典都有带 id 的类，牛津高阶对应的是 `d-oaldict` 

```css
.d-oaldict {
  color: #eafaea;
}
```
