### DISCUSSION TITLE
【dark模式】简单毛玻璃

### DISCUSSION THREAD

**Discussion by swithun-liu** [crimx/ext-saladict#1813] [Theme 主题]
目前只适配了「黑暗模式」
<img width="715" alt="image" src="https://user-images.githubusercontent.com/42160297/184527193-a38a26d6-0903-4b8f-9d9c-7f2c4a9f0121.png">
**适合常看黑色背景网页（比如我是使用 [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) 插件强制转换没有黑色模式的网页）的情况**

<summary>2022/9/10<summary>

|黑色网页效果|白色网页效果|独立面板|
|-|-|-|
|<img width="732" alt="image" src="https://user-images.githubusercontent.com/42160297/189469834-d333b02d-1475-438c-b198-8af839590955.png">|<img width="712" alt="image" src="https://user-images.githubusercontent.com/42160297/189469825-ff1de6dd-077a-4d87-b601-c7085598cc58.png">|<img width="585" alt="image" src="https://user-images.githubusercontent.com/42160297/189469856-4460ceae-99a9-4197-9f07-d1191137ea16.png">|

问题：独立面板和白色背景情况下，由于面板本身的白色底色，显示为灰色， 可以调整   `background: #1818189c !important;` -> `    background: #181818cc !important;` ，三种情况下的效果都是接近的黑色，但是*黑色网页*时透明效果变差，自行选择。「目前暂无更好的解决方式」

```css
.menuBar {
    background-color: #00000000;
}
.dictPanel-Root {
    --color-brand: #00000000 !important;
    --color-rgb-background: #00000000 !important;
    --color-font: #ddd !important;
    --color-divider: #4d4748 !important;

    background: linear-gradient(145deg, #00000000, #00000000) !important;
    background-image: linear-gradient(145deg, #00000000, #00000000);
    background: #1818189c !important;

    border: 0.5px solid #ffffff33;
    border-radius: 7px;

    box-shadow: rgb(0 0 0) 0 0px 30px 10px;

    backdrop-filter: blur(10px);
}
.darkMode .saladict-theme {
    background-color: #00000000 !important;
    --color-background: #00000000 !important;
    --darkreader-bg--color-background: #00000000;
}
.mtaBox-DrawerBtn {
    background-color: #00000000;
}
```

<details>
<summary>旧 2022/8/13</summary>
<img width="771" alt="image" src="https://user-images.githubusercontent.com/42160297/184504127-8369b8ae-4a16-4b4d-a74d-6cd1dbd2a7e8.png">

```css
.menuBar {
  background-color: #00000000;
}
.dictPanel-Root {
  --color-brand: #00000000 !important;
  --color-rgb-background: #00000000 !important;
  --color-font: #ddd !important;
  --color-divider: #4d4748 !important;

  border-radius: 7px;
  background: linear-gradient(145deg, #3e3e3e, #4a4a4a);
  box-shadow: rgb(0 0 0) 0 0px 30px 10px;

}
.darkMode .saladict-theme {
    background-color: #00000000 !important;
    --color-background: #00000000 !important;
    --darkreader-bg--color-background: #00000000;

}
.dictPanel-Root {
    background-image: linear-gradient(145deg, rgb(73 77 79 / 72%), rgb(80 85 87));
    backdrop-filter: blur(6px);
}
.mtaBox-DrawerBtn {
    background-color: #00000000;
}
```
</details>

**Comment by crimx** [comment]
好厉害🤩

**Reply by X-Ray1128** [reply]
请问为啥独立面板的主题会不一样

**Comment by X-Ray1128** [comment]
请问为啥独立面板的主题会不一样

**Reply by swithun-liu** [reply]
有截图吗

**Reply by X-Ray1128** [reply]
![image](https://user-images.githubusercontent.com/101329336/189468775-c78a5921-9ddc-4d53-807b-c7bc7f6ef005.png)
这是独立窗口面板
![image](https://user-images.githubusercontent.com/101329336/189468807-f5986770-2cac-4ebf-a95a-8d61ea713537.png)
这是正常翻译面板

**Comment by X-Ray1128** [comment]
![image](https://user-images.githubusercontent.com/101329336/189468756-4e9defea-e162-41e9-a17f-37bdcba492a4.png)
这是独立窗口的面板

**Reply by swithun-liu** [reply]
独立面板和白色背景情况下，由于面板本身的白色底色，显示为灰色， 可以调整   `background: #1818189c !important;` -> `    background: #181818cc !important;` ，三种情况下的效果都是接近的黑色，但是*黑色网页*时透明效果变差，自行选择。「目前暂无更好的解决方式」

**Comment by rehman-talha** [comment]
please help me with dark mode for pdf. Thanks  in advance.

请帮助我使用 pdf 的暗模式。 提前致谢

Please build a dark mode for pdf option. Thank you. I love Saladict. 
请为 pdf 选项建立一个暗模式。 谢谢你。 我喜欢沙拉迪克。

@swithun-liu 
@crimx

**Reply by swithun-liu** [reply]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/42160297/197343012-a2afe46a-cf8b-43b5-bde2-a583ea0562b5.png">

change `9c` to `cc`, so when the document or the webpage is a white background, it will be better

The effect is as follows

<img width="500" alt="image" src="https://user-images.githubusercontent.com/42160297/197342943-71672656-b9f3-4362-b50f-8a42b80619bc.png">

**Reply by rehman-talha** [reply]
Thank you, but I don't know how to get to this code. I have no coding experience!

**Reply by swithun-liu** [reply]
> Thank you, but I don't know how to get to this code. I have no coding experience!

<img width="300" alt="image" src="https://user-images.githubusercontent.com/42160297/197399047-87419709-f1cf-48cc-8505-2ee13f394f6a.png">

just copy it from here

<img width="300" alt="image" src="https://user-images.githubusercontent.com/42160297/197399077-4d68a1e8-3f3c-409c-b33a-7ad7343828d2.png">

then paste it to here

**Reply by rehman-talha** [reply]
thanks, it looks cool. what I wanted to say was how to make the background of this pdf dark? This is a book that I have opened.
![image](https://user-images.githubusercontent.com/93119114/197399498-e7226103-e9c9-4dd2-a0e4-0965cf9f6089.png)

**Reply by swithun-liu** [reply]
oh, I see, but I don't familiar with that

**Reply by rehman-talha** [reply]
Okays, Thank you for helping me out.

**Reply by crimx** [reply]
It seems not possible by default. This [workaround](https://github.com/mozilla/pdf.js/issues/2071#issuecomment-830446509) works but **bookmarklet** is not supported on Browser Extensions. Saladict has to implement it as a new option. 

If you want to try it now, press <kbd>F12</kbd> on the PDF page, paste below on the `console` input and press <kbd>↵</kbd>

```js
document.getElementById('viewer').style.filter = 'invert(64%) contrast(228%) brightness(80%) hue-rotate(180deg)'
```

**Comment by rehman-talha** [comment]
Okay Thanks

**Comment by sodayamajk** [comment]
![QQ截图20221214124313](https://user-images.githubusercontent.com/97017158/207507851-faddf3da-318c-4938-bf14-5fef0f94b51b.jpg)
将博主的又改了一下，透明＋字体描边效果

.menuBar {
    background-color: #00000000;
}
.dictPanel-Root {
        color: white;

        font-size: 40px;

        text-shadow: -1px 1px 0 #000, 1px 1px 0 #000, 1px -1px 0 #000,

          -1px -1px 0 #000;

    background: linear-gradient(145deg, #00000000, #00000000) !important;
    background-image: linear-gradient(145deg, #00000000, #00000000);
    background: #1818189c !important;

    border: 0.5px solid #ffffff33;
    border-radius: 7px;

    box-shadow: rgb(0 0 0) 0 0px 1px 1px;

    backdrop-filter: blur(0px);
}
.darkMode .saladict-theme {
    background-color: #00000000 !important;
    --color-background: #00000000 !important;
    --darkreader-bg--color-background: #00000000;
}
.mtaBox-DrawerBtn {
    background-color: #00000000;
}

**Comment by sodayamajk** [comment]
但是不知道博主有没有方法将独立窗口也变透明啊

**Comment by sodayamajk** [comment]
![QQ截图20221214124541](https://user-images.githubusercontent.com/97017158/207508256-70daf705-b0d8-486e-a081-a21ac97beb29.jpg)

**Comment by l3ony2k** [comment]
分享 + 备份一下我改的效果 : )

![Snipaste_2023-03-07_17-28-19](https://user-images.githubusercontent.com/58762081/223380471-f22b444e-7c95-4f31-b34f-db8757bb69f7.png)

```css
.menuBar {
    background-color: #00000000;
}
.dictPanel-Root {
    --color-brand: #F9690E !important;
    --color-rgb-background: #00000000 !important;
    --color-font: #ddd !important;
    --color-divider: #4d4748 !important;

    --darkreader-bg--color-background: #00000000;
    --darkreader-border--color-font: #333333 !important;
    --darkreader-bg--color-divider: #333333 !important;
    --darkreader-border--color-divider: #333333 !important;

    background: linear-gradient(145deg, #00000000, #00000000) !important;
    background-image: linear-gradient(145deg, #00000000, #00000000);
    background: #0000009c !important;

    border: 1px solid #33333333;
    border-radius: 7px;

    /*box-shadow: rgb(0 0 0) 0 0px 30px 10px;*/

    backdrop-filter: blur(25px);
}
.darkMode .saladict-theme {
    background-color: #00000000 !important;
    --color-background: #00000000 !important;
}
.mtaBox-DrawerBtn {
    background-color: #00000000;
}
```
