### DISCUSSION TITLE
Custom Theme [自定义主题] 透明 GitHub 暗黑模式

### DISCUSSION THREAD

**Discussion by ElapseRecall** [crimx/ext-saladict#2068] [Theme 主题]
**复制代码到「设置** -> 查词面板 -> _**自定义查词面板样式」即可，如果有不需要的样式可以自行调整参数即可。**

```css
/* 主面板 */
.dictPanel-Root {
    --color-brand: #1c2128 !important; /* 菜单栏背景颜色 */
    --color-background: #22272e99 !important; /* 词典背景颜色 */
    --color-font: #adbac7 !important; /* 全局字体颜色 */
    width: 450px !important; /* 面板宽度 */
    background-color: #00000099; /* 底图颜色 */
    border-radius: 8px;
}

/* 隐藏侧边滚动条 */
.fancy-scrollbar::-webkit-scrollbar {
    display: none; /* 适用于 Blink 或 WebKit 的浏览器 */
}
.fancy-scrollbar {
    scrollbar-width: none; /* 适用于 Firefox */
}

/* 菜单栏调整 */
.menuBar {
    height: 36px;
    padding: 0;
}

/* 查词记录按钮 */
.menuBar-Btn-dir {
    width: 30px;
    padding: 8px;
}

/* 搜索框 */
.menuBar-SearchBox {
    width: 135px;
    height: 26px;
    border-radius: 4px;
}

/* 菜单栏按钮鼠标悬浮变色 */
.menuBar > button {
    border-radius: 4px;
    margin: 3px;
}
.menuBar > button:hover {
    background-color: #347d39;
}
.menuBar > button:last-of-type:hover {
    background-color: #e5534b80;
}
.menuBar-Btn {
    border-radius: 4px;
    margin: 3px;
}
.menuBar-Btn:hover {
    background-color: #539bf5;
}

/* 更改查词记录按钮鼠标图标 */
:disabled > svg {
    cursor: not-allowed;
}

/* 词典区 */
.dictItem {
    margin: 6px;
    border-radius: 8px;
}

/* 词典栏 */
.dictItemHead {
    border: none;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
    background-color: #22272e;
    height: 32px;
    padding: 0 6px;
    align-items: center;
    position: static;
}

/* 词典名 */
.dictItemHead-Title > a {
    color: #539bf5;
}

/* 词典图片 */
.dictItemHead-Logo {
    border-radius: 4px;
}

/* 按钮垂直对齐 */
.dictItemHead-Menus_Btn {
    margin: 0;
}
.hoverBox-Container {
    display: flex;
}

/* 占位块 */
.dictItemHead-EmptyArea {
    cursor: pointer;
}

/* 详情区 */
.dictItem-Body {
    min-height: 16px;
}

/* 鼠标悬浮变色 */
.dictItemHead-Menus_Btn:hover > svg {
    background-color: #539bf5;
    border-radius: 4px;
}
.dictItemHead-FoldArrowBtn:hover {
    background-color: #347d39;
    border-radius: 4px;
}

/* 上下小箭头区 */
.mtaBox-DrawerBtn,
.waveformBox-DrawerBtn {
    border: none;
    background-color: #22272e99;
    display: none; /* 如需要小箭头可以删除 */
}

/* 更改全局字体 */
.saladict-panel {
    font-family: 'HarmonyOS Sans SC'; /* 字体名填自己电脑上安装的 */
}

/* 隐藏有道词典星星 */
.dictYoudao-Stars {
    display: none;
}
```
