### DISCUSSION TITLE
Custom Theme 极简主题-修改字体-微调-藏蓝-圆角

### DISCUSSION THREAD

**Discussion by allinu** [crimx/ext-saladict#2073] [Theme 主题]
使用锤子字体，微调一些高度和圆角，整体变化不大

锤子科技字体可以到这里下载[【下载链接】](https://github.com/allinu/TMP/tree/main/fonts) 其中 Smartisan 的就是。

__感谢锤子科技的贡献，非授权字体，侵权联系删除。__

__另外，windows 推荐使用 [MacType](https://www.mactype.net/) 优化字体渲染。__

![image](https://github.com/crimx/ext-saladict/assets/32992109/85ff359c-cf4a-411d-9872-ba839952def5)

代码如下
```css
/* 复制代码到「设置 -> 查词面板 -> 自定义查词面板样式」即可。*/
.dictRoot {
  font-family: "Smartisan CNS" !important;
  font-size: 15px;
}
.menuBar {
	background-color: #052946;
	height: 35px;
}
.menuBar-SearchBox {
	border-radius: 3px;
	padding: 2px 5px;
	background-color: rgb(225 225 225 / 36%);
}
.dictItem {
  padding: 10px 10px 0 10px;
}
.dictItemHead {
	display: flex;
	height: 30px;
	padding-left: 10px;
	align-items: center;
	background-color: #d9d9d9;
	border-radius: 3px;
}
.dictItemHead-Title {
	font-size: 15px;
	font-weight: bold;
}
```
