### ISSUE TITLE
沙拉图标大小以及透明度

### ISSUE THREAD

**Issue by ly13717** [crimx/ext-saladict#1395]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

沙拉图标太大，遮挡部分网页内容

## 理想情况下，沙拉查词应该怎么做

希望可以设置沙拉图标大小，以及可设置图标半透明度。

**Comment by ipconfig12138** [comment]
同意,同意

**Comment by crimx** [comment]
沙拉图标的位置可以在设置「查词面板」调整。

沙拉图标的样式可以通过设置「查词面板」「自定义查词面板样式」调整，例子：

```css
.saladbowl {
  width: 20px;
  height: 20px;
  opacity: 0.6;
}

.saladbowl > svg {
  width: 20px;
  height: 20px;
}
```
