### ISSUE TITLE
Custom Theme [自定义主题] [超级美观]

### ISSUE THREAD

**Issue by honghuhu** [crimx/ext-saladict#1427]
### Discussed in https://github.com/crimx/ext-saladict/discussions/1422

<div type='discussions-op-text'>

<sup>Originally posted by **honghuhu** August  6, 2021</sup>
```CSS
/* 复制代码到「设置 -> 查词面板 -> 自定义查词面板样式」即可。*/
body {
    background: #c0531c !important
}

header,
section[class^="dictItem"],
button[class^="mtaBox-DrawerBtn"] {
    background-color: #ffffff00 !important
}

/* 不同区域词典 */
.dictJukuu-Ori {
    color: rebeccapurple
}

.dictJukuu-Src {
    color: #1fa7a2
}

.dictBing-Inf {
    color: #006788
}

/* 菜单按钮 */
[class^="menuBar"] {
    fill: #177ddc;
    color: #177ddc
}

/* 整个面板 */
select, .darkMode .saladict-theme {
    --color-font: black;
    --color-background: #22222200;
    --color-font-grey: black
}

/* 调出自己喜欢的样式 */
.dictPanel-Root {
    /* 复制评论里的样式 | 随意变换颜色，只需替换下边样式即可 */
    background: radial-gradient(ellipse farthest-side at 76% 77%, rgba(245, 228, 212, 0.25) 4%, rgba(255, 255, 255, 0) calc(4% + 1px)), radial-gradient(circle at 76% 40%, #fef6ec 4%, rgba(255, 255, 255, 0) 4.18%), linear-gradient(135deg, #ff0000 0%, #000036 100%), radial-gradient(ellipse at 28% 0%, #ffcfac 0%, rgba(98, 149, 144, 0.5) 100%), linear-gradient(180deg, #cd6e8a 0%, #f5eab0 69%, #d6c8a2 70%, #a2758d 100%); background-blend-mode: normal, normal, screen, overlay, normal
}
```
