### ISSUE TITLE
超好看的暗色主题

### ISSUE THREAD

**Issue by honghuhu** [crimx/ext-saladict#1560]
```css
body {
    background: #ffd4b5de !important
}

header,
section[class^="dictItem"],
button[class^="mtaBox-DrawerBtn"] {
    background-color: #ffffff00 !important
}

/* 菜单按钮 */
[class^="menuBar"] {
    fill : #ff00c8;
    color: white
}

/* 整个面板 */
.saladict-theme {
    --color-font     : white !important;
    --color-font-grey: yellow !important
}

/* 调出自己喜欢的样式 */
/* 词典头部&提示框&词典面板 */
.dictItemHead-Title a,
.floatBox-Container,
.dictPanel-Root {
    --color-background: #22222200 !important;
    /* 复制评论里的样式 | 随意变换颜色，只需替换下边样式即可 */
    background        : linear-gradient(45deg, rgb(0 0 0) 10%, rgb(25 48 52) 40%, rgb(0 0 0) 40%, rgb(0 0 0) 60%, rgb(0 0 0) 60%, rgb(118 0 149) 65%, rgb(0 0 0) 65%, rgb(0 0 0) 90%) !important
}

.entryBox {
    border: 0px solid red;
    background: linear-gradient(90deg, red 50%, transparent 0) repeat-x,
        linear-gradient(90deg, rgb(0, 252, 0) 50%, transparent 0) repeat-x,
        linear-gradient(0deg, purple 50%, transparent 0) repeat-y,
        linear-gradient(0deg, orange 50%, transparent 0) repeat-y;
    background-size    : 10px 2px, 10px 2px, 2px 10px, 2px 10px;
    background-position: 0 0, 0 100%, 0 0, 100% 0;
    animation          : entryBoxAni 500ms infinite linear !important;
}

@keyframes entryBoxAni {
    100% {
        background-position: 10px 0, -10px 100%, 0 -10px, 100% 10px;
    }
}
```

_Originally posted by @honghuhu in https://github.com/crimx/ext-saladict/discussions/1422#discussioncomment-1536835_
