### ISSUE TITLE
悬浮取词 和 普通划词 显示不一样的查词面板（两个面板都可以单独设置“外观CSS 习惯  词典 发音”互不影响）让youtube字幕悬浮查词（短时间内只显示最精简的解释）和划词显示（划词显示详细解释）的内容不同

### ISSUE THREAD

**Issue by k22725** [crimx/ext-saladict#1858]
## 设备信息
- 操作系统: Win10
- 浏览器版本: Chrome 105.0.5195.127
- 沙拉查词版本: v7.20.0

## 请描述目前使用沙拉查词遇到什么不便
目前的悬浮取词 从属于 普通划词（得到的结果和划词一样） 
划词（点划选中）和 取词（移动到词的位置） 是两种动作 理应分开
不在输入框划词还好说[但是悬浮取词还是会影响输入框](https://github.com/crimx/ext-saladict/issues/1857)不知道技术上能不能实现让悬浮取词不影响输入框

让youtube字幕悬浮查词（短时间内只显示最精简的解释）和划词显示（划词显示详细解释）的内容不同
鄙人目前是 让沙拉专门悬浮查词用
至于详细解释就用 额外装的一个[扩展](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91%E6%9F%AF%E6%9E%97%E6%96%AF%E8%AF%8D%E5%85%B8%20%E6%89%87%E8%B4%9D%E7%94%9F%E8%AF%8D%E6%9C%AC/mkohdjbfagmlcaclajmadgkojelkbbfj)https://github.com/oyyd/youdao-collins-chrome-extension
此扩展短小精悍 简洁的界面查词神速 就是功能稍少了点
沙拉的 必应词典 汉典 查询速度时快时慢 有时等半天才出结果 或者 啥也没有只能干瞪眼 不知道是不是墙在作祟 微软服务在West Korea经常性的龟速必应词典也不免受影响 汉典就搞不懂了 [官网](https://www.zdic.net/)查速度不慢 但是调用沙拉的汉典词典查就碰运气了 查同样的汉字词在同一天同一个小时内 就是有时很快有时就不出结果 不知道是什么原因导致的

## 理想情况下，沙拉查词应该怎么做
悬浮取词、普通划词、右上弹窗、独立词典窗口 ——这4种显示方式可以单独设置（查词面板 查词习惯  词典 发音）互不影响

## 油土鳖 字幕实时翻译 ①
配合【YouTube™ 双字幕】扩展程序 https://www.dual-subtitles.com/zh-Hans/
我的【YouTube™ 双字幕】设置是
字体：黑体（翻译字幕） Arial（视频字幕）
字号：20（翻译字幕、视频字幕）
颜色：FFFFFF80（翻译字幕、视频字幕）
背景：00000080（翻译字幕、视频字幕）

以下是鄙人在【暗黑模式】下【词典只选了 百度翻译，划词语言只选 英文】的CSS（可以实现 悬浮显示几秒后自动隐藏 便于在youtube中快速把选中的单词翻成中文并且弹出的内容少对观看视频影响小 节省宝贵时间）

```css
.entryBox-Wrap {padding-top: unset;}
.entryBox {border: 0;    margin-bottom: 0;    padding: 0;}
.MachineTrans-Lines {padding-left: 0;    margin: 0;}
.MachineTrans-Lines p {margin: 0em;}
.dictItem-BodyMesure>:first-child{margin-top: 0px !important;}
.dictItem-BodyMesure>:last-child{margin-bottom: 0px !important;}
.dictPanel-Root.saladict-panel {width: fit-content !important;    height: fit-content !important;}
.dictItem-Body {line-height: 1;    padding: 0;    height: fit-content !important;}
.dictPanel-Root {box-shadow: none !important;    border-radius: unset;}
.bknr, .jnr, .wknr {margin: 0;}
.contentslot, .mpuslot_b {margin-top: 0;}
.darkMode .saladict-theme {--color-background: #00000000!important;}
p {
    padding-left: 0;
    width: fit-content!important;
    /* 几秒后隐藏 */
    animation: mymove 3s;
    animation-fill-mode: forwards;
}
@keyframes mymove {to {height: 0; width: 0;}}
/* 字体 */
.dictRoot {
    font: 29.375px SimHei;
} 
/* 颜色 */
.dictPanel-Root {
    --color-font: #FFFFFF80!important;
    background: #00000080!important;
}
/* 隐藏元素 */    
.menuBar,
.saladict-Speaker,
.dictItemHead,
.MachineTrans-lang-en  {display:none;}
```

## 油土鳖 字幕实时翻译 ②
https://addons.mozilla.org/zh-CN/firefox/addon/youtube-subtitle-position/  （这是一个可以记住Youtube字幕位置的Firefox扩展，安装成功后会在YouTube播放器控制条上多出个红色按钮 点开按钮会出现 有9个方框【分别对应“左上 上 右上 左 中 右 左下 下 右下”9个位置，可快速把字幕定到相应位置】5个白色矩形【分别对应“左对齐 居中对齐 右对齐（对齐对自动字幕生效）上移 下移”】 Chrome商店没找到类似功能的扩展）
下载文件 把 .xpi 后缀改为 .zip 拖到 chrome://extensions/ 页面安装扩展（如果没安装 应该是页面右上角“开发者模式”开关没开启  开启开关后 刷新下页面再拖一遍文件进去就能安装了）安装成功后 会提示两条错误（Unrecognized manifest key 'browser_specific_settings'.    Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.）不过没关系 不影响使用（如果有哪位大侠知道这俩错误啥意思 什么原因引起的 恳请不吝赐教）

https://saladict.crimx.com/tips.html#youtube （https://greasyfork.org/en/scripts/402598-fixed-youtube-captions）
介绍的油猴脚本 在YouTube字幕上会显示 小手手
鄙人发现一个更完美的办法
在点开下面链接
https://stackoverflow.com/questions/40165879/how-make-youtube-subtitles-selectable
键盘 “ Ctrl + F ” 快捷键搜 Ilya 就可以找到代码了
把代码复制粘贴到 [油猴子](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo)新建的用户脚本中保存就OK啦！（该脚本可以让字幕可选择 并且 不显示 小手手）

以下是 Ilya 分享的代码

```js
// ==UserScript==
// @name         make youtube caption selectable
// @namespace    none
// @version      0.2
// @description  Use this script if you want be able to select youtube captions/subtitles!
// @author       You
// @match        https://www.youtube.com/watch?*
// @grant        none
// @require      none
// ==/UserScript==

!function() {
  setInterval(make_subtitles_selectable, 250);
  function make_subtitles_selectable(){
    elem=document.querySelector("div.caption-window");
    if(elem!=null){
        elem.addEventListener("mousedown", function (event) {
            event.stopPropagation();
        }, true);
        elem.setAttribute("draggable", "false");
        elem.style.userSelect="text";
        elem.style.cursor="text";
        elem.setAttribute("selectable", "true");
    }
    elem=document.querySelector("span.ytp-caption-segment:not([selectable='true']");
    if(elem!=null){
        elem.style.userSelect="text";
        elem.style.cursor="text";
        elem.setAttribute("selectable", "true");
    }
    elem=document.querySelector("#caption-window-1:not([selectable='true']");
    if(elem!=null){
        elem.addEventListener("mousedown", function (event) {
            event.stopPropagation();
        }, true);
        elem.setAttribute("selectable", "true");
        elem.setAttribute("draggable", "false");
    }
}
}()
```
