### ISSUE TITLE
面板自定义样式的例子

### ISSUE THREAD

**Issue by photkey** [crimx/ext-saladict#658]
https://github.com/crimx/ext-saladict/wiki/PanelCSS
简单的全黑色,这个样式的例子是空白的，请求一个例子。
![Snipaste_2020-02-20_22-33-59](https://user-images.githubusercontent.com/60434581/74944581-39ea2b80-5431-11ea-8a01-1aa4d976895b.png)

**Comment by crimx** [comment]
现在已自带黑暗模式，故不再需要。

**Comment by photkey** [comment]
![Snipaste_2020-02-20_22-59-11](https://user-images.githubusercontent.com/60434581/74946695-ab77a900-5434-11ea-824a-a5feaea1e4ea.png)

我想要修改 顶部这里的颜色，可以自定义修改吗？可以的话 能否给个例子，谢谢！

**Comment by crimx** [comment]
```css
.menuBar {
  background-color: #333;
}
```

**Comment by crimx** [comment]
也可以调整面板色系

```css
.dictPanel-Root {
  --color-brand: #333 !important;
}
```
