### ISSUE TITLE
搜索框字体

### ISSUE THREAD

**Issue by vegeta100** [crimx/ext-saladict#721]
希望可以加上搜索框字体**大小调整**的功能。在整句google翻译的时候，一般是开搜索框的。这样就能英文中文对比一番，快速地对段落里的多个单词有大概印象。也是一个学外语的办法。但是搜索框的字体好像是13px，有点小了。加上这个功能，搜索框的原文就看得比较清楚了。

**Comment by crimx** [comment]
你可以在查词面板设置中自定义样式

```css
.mtaBox-TextArea {
  font-size: 20px;
}
```
