### ISSUE TITLE
希望搜索框字体 词典字体这两项可以分开调整大小

### ISSUE THREAD

**Issue by vegeta100** [crimx/ext-saladict#757]
昨天升级了最新的版本，发现搜索框字体和词典字体的设置**捆绑**在一起了。设置了词典字体的大小，搜索框的字体会跟着变。

而在自定义查词面板样式里加上这个样式，也没起到效果
.mtaBox-TextArea {
  font-size: 20px;
}

有个学习习惯是，翻译一整段，中英文对比一番，快速地对段落里的多个英文单词有大概的印象。这个过程主要是把注意力放在英文上的。也就是目光更多地**聚焦**到搜索框里的英文，我亲身的体会是，这需要把搜索框的字体设得比词典的更大一些。

**Comment by crimx** [comment]
改为

```css
.mtaBox-TextArea {
  font-size: 20px ! important;
}
```
