### ISSUE TITLE
双击选词时图标模糊

### ISSUE THREAD

**Issue by RemRemRemRe** [crimx/ext-saladict#867]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Firefox77] 
- 沙拉查词版本: [v7.13.3] 

## 描述问题

双击选词时，图标总有一个从模糊到清晰的过程

## 期待的正常行为

双击选词时 图标永远是清晰的

## 截图

![图片](https://user-images.githubusercontent.com/20263103/85361829-849ac200-b54f-11ea-8d3b-a206dcb09cf5.png)

![图片](https://user-images.githubusercontent.com/20263103/85361836-895f7600-b54f-11ea-9abc-8dc796d8b1d0.png)

**Comment by crimx** [comment]
这个应该是 Firefox 硬件加速与你的显卡不太兼容。

**Comment by crimx** [comment]
你可以有以下几个选择，任选一个应该都可以解决。

- 设置中关闭沙拉查词动画。
- 关闭沙拉图标动画。
   在设置「查词面板」👉「自定义查词面板样式」中添加
   ```css
   .saladbowl-enter-active > svg {
     animation: none !important;
   }
   ```
- 关闭 Firefox 硬件加速。
- 更换浏览器。
